# 开启此配置会导致index.html不能默认访问
#spring:
#  mvc:
#    static-path-pattern: /res/**
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
# 以后所有的请求都必须以/world开始
server:
  servlet:
    context-path: /world
